<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/12/27 08:28:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sfgame',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
